package com.example.notification.engine.model

import androidx.annotation.Keep

/**
 * Source stream from which the event originated.
 * Aids in deduplication across redundant paths (e.g. Realtime + FCM arriving simultaneously).
 */
@Keep
enum class NotificationOrigin {
    /** Delivered via Supabase WebSocket / Realtime Channel. */
    REALTIME,

    /** Delivered via Firebase Cloud Messaging push payload. */
    FCM,

    /** Emitted by a background WorkManager job. */
    WORK_MANAGER,

    /** Generated directly in local client UI / Repository. */
    LOCAL_UI,

    /** Generated by an Android Foreground Service (e.g. CallForegroundService, PanalinkRealtimeService). */
    SYSTEM_SERVICE
}
